### ISSUE TITLE
Fatal error: Uncaught Error: Class 'System\Request' not found

### ISSUE THREAD

**Issue by amriunix** [nezamy/route#11]
Fatal error: Uncaught Error: Class 'System\Request' not found in /var/www/html/vendor/nezamy/route/system/startup.php:12 Stack trace: #0 /var/www/html/vendor/nezamy/route/index.php(2): require() #1 {main} thrown in /var/www/html/vendor/nezamy/route/system/startup.php on line 12

OS : Ubuntu
PHP : PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**Comment by nertilzhuri** [comment]
I just had the same problem, I don't know why it happens but I fixed it by going on the system/startup.php and adding the following lines of code:

`require "Request.php";`
`require "Route.php";`

after the :

`require "App.php";`

Hope it helps, and a word from the author about this issue would be appreciated in hopes of not having any further problems.

**Comment by nezamy** [comment]
If you are using composer. make sure you created index.php in root  with content
```php
<?php
define('DS', DIRECTORY_SEPARATOR, true);
define('BASE_PATH', __DIR__ . DS, TRUE);

require BASE_PATH.'vendor/autoload.php';

$app            = System\App::instance();
$app->request   = System\Request::instance();
$app->route     = System\Route::instance($app->request);

$route          = $app->route;

$route->any('/', function() {
    echo 'Hello World';
});

$route->end();
```

If you download it just use it without any changes
