### ISSUE TITLE
Shortcode function url()

### ISSUE THREAD

**Issue by phuclh** [nezamy/route#15]
I am using XAMPP to run my project. Here is my URL for my project: `http://localhost/cms`

When I used the function `url()` to show domain url, then the result is `http://localhost//`. Is there any way to make it show `http://localhost/cms/`

**Comment by nezamy** [comment]
Run this command on cmd 
```
php -S localhost:8000 -t C:\xampp\htdocs\cms
```
then run localhost:8000 on your browser

**Comment by phuclh** [comment]
Is there any way to do if I want to keep my URL like this: `http://localhost/cms/`?

**Comment by nezamy** [comment]
Yes, Just Update your system/Request.php file 
Under line 52
I'm added this lines 
```php
       if($this->servername == 'localhost'){
            $this->url = strtolower(
                $this->protocol . '://' . $this->servername . 
                str_replace($this->path, '', $this->server['REQUEST_URI'])
            );
        }
```

**Comment by phuclh** [comment]
Hope you can update it in next version :D. Your package is amazing. Thank you.
