### ISSUE TITLE
Callable error when run in docker container

### ISSUE THREAD

**Issue by iamapinan** [nezamy/route#19]
**Fatal error: Uncaught Exception: Callable error on Controllers\Home -> index** 
My route setting run in _/var/www/app/route/web.php_
I called to controllers in _/var/www/app/controllers/Home.php_
**Code in Home.php**
```
<?php
namespace Controllers;

class Home {
    public function index() {
        echo render('home.tpl');
    }
}
```
Help me please.

**Comment by nezamy** [comment]
What the root folder www or app, and lets me see the route code.
