### ISSUE TITLE
Access variable outside of groups

### ISSUE THREAD

**Issue by PeterPan73** [nezamy/route#22]
Hi everyone,
I try to access a variable that is in a group -> get, but I can not access it from the outside.
I use a code from the examples - groups with parameters.

```
$route->group('/{lang}?:isoCode2', function($lang)
{
    $default = $lang;

    if(!in_array($lang, ['ar', 'en'])){
        $default = 'en';
    }

        $this->get('/', function($lang) use($default){
        echo "lang in request is $lang<br>";
        echo "include page_{$default}.php";
    });

    $this->get('/page/{name}/', function($lang, $name)
    {
	$test_var = $this->app->request->args;
        pre(func_get_args());
        pre($this->app->request->args);
    });
});
```

**pre($test_var)**;

**Comment by nezamy** [comment]
You can not access variables outside function it's not global.
If you want access the request args do this 
```php
pre(app('request')->args);
``` 
But it will work only if the route matched.

Tell me why you need call this outside?
