### ISSUE TITLE
Have you checked Following routers?

### ISSUE THREAD

**Issue by abmmhasan** [nezamy/route#26]
https://github.com/bramus/router
https://github.com/klein/klein.php

Well those are some of the good routers. Though Klein lacks OOP where bramous lacks request/response thingy. 
Your router is good except I would ask if you can check those you can add lot more functionality+what they lack.

**Comment by nezamy** [comment]
Hello @abmmhasan ,
I already working on V2 with some features like auth, roles, modules and subdomains.

**Comment by abmmhasan** [comment]
That is great! But I think the router need the following improvement for now:
Change
```
$route->get_post('/', function(){
    // Only GET and POST request
});
```

to this:
```
$route->request('get|post','/', function(){
    // Only GET and POST request
});
```
It will expand the possibility. And will reduce your code in router.

**Comment by nezamy** [comment]
You can do that 
```php
$route->get_post_put('/', function(){
    // Only GET, POST and PUT request
});
//Or
$route->route(['GET', 'POST', 'PUT'], '/', function(){
    // Only GET, POST and PUT request
});
```
