### ISSUE TITLE
Multilingual router

### ISSUE THREAD

**Issue by perspolise** [nezamy/route#28]
Hello,
How do work route for multilingual system?!

without multilingual i choose this method and work true:
```
$route->get('/, 'App\Front\Controller\Home\IndexController@index');
$route->get('/account/login/', 'App\Front\Controller\LoginController@index');
$route->post('/account/login/', 'App\Front\Controller\LoginController@login'); 
```
Now In action i need to create url like this:

For default language(en):
`http://mywebsite/  OR  http://mywebsite/account/login `
For Another language(ar):
`http://mywebsite/ar  OR  http://mywebsite/ar/account/login `

**Comment by vahidkaargar** [comment]
Hi,
you can get language by params

$route->post('/?/account/login/',
'App\Front\Controller\LoginController@login');

**Comment by vahidkaargar** [comment]
Hi,
you can get language by params

`$route->get('/?/account/login/','App\Front\Controller\LoginController@login');`

**Comment by nezamy** [comment]
@perspolise Use group with parameters and make `lang` parameter optional
```php
$route->group('/{lang}?:isoCode2', function($lang)
{
    $default = $lang;

    if (!in_array($lang, ['ar', 'en'])) {
        $default = 'en';
    }
    app()->language = $default;

    $this->get('/', 'App\Front\Controller\Home\IndexController@index');
    $this->get('/account/login/', 'App\Front\Controller\LoginController@index');
    $this->post('/account/login/', 'App\Front\Controller\LoginController@login');
});
```
You can get language from anywhere by calling ` app('language')` or `app()->language`

**Comment by mojifier** [comment]
@nezamy : Thanks I check But your code not work for parameters Like This:

```
$route->group('/mvc/{lang}?:isoCode2', function($lang)
{
    $default = $lang;

    if (!in_array($lang, ['ar', 'en'])) {
        $default = 'en';
    }
    app()->language = $default;

    $this->get('/account/verifyresetpassword/?/?', 'App\Catalog\Controller\Account\VerifyPasswordController@index');
});
```

my url is:
`localhost/mvc/account/verifyresetpassword/2/7b424d2408adc10571d5cd876e2f372bad06b7c3`

In verifypassword controller I have:
```
class VerifyPasswordController extends \App\Core\Controller
{
    public function index($customer_id, $verification_code)
    {
      echo $customer_id.'<br>'.$verification_code;
     }
}

```

in output i see:

`2`

and I cant see verification code. if we add language to url like this:

`localhost/mvc/ar/account/verifyresetpassword/2/7b424d2408adc10571d5cd876e2f372bad06b7c3`

I see:

```
ar 
2
```
and I cant see verification code.
How do can i fix this problem and show/print customer_id and verification_code?!

**Comment by nezamy** [comment]
@perspolise Just add the 3rd parameter to the controller method  (index)
Because you use a group with parameters, so you have one arg from lang and two from `/account/verifyresetpassword/?/?` route 
```php
<?php
class VerifyPasswordController extends \App\Core\Controller
{
    public function index($lang, $customer_id, $verification_code) {
        // lang from uri
         pre($lang);
         // default lang
         pre(app()->language, 2);
         echo $customer_id.'<br>'.$verification_code;
     }
}
```
Also you can use middleware to set default language 

```php
<?php
$route->before('/mvc', function ($lang) {
    $default = $lang;

    if (!in_array($lang, ['ar', 'en'])) {
        $default = 'en';
    }
    app()->language = $default;
});

$route->group('/mvc/{lang}?:isoCode2', function() {
    $this->get('/account/verifyresetpassword/?/?', 'App\Catalog\Controller\Account\VerifyPasswordController@index');
});
```
