### ISSUE TITLE
Version for php <5.3

### ISSUE THREAD

**Issue by xiaolp** [nezamy/route#3]
hi,
could u convert this to support php version <5.3?

**Comment by nezamy** [comment]
Why you still using php version <5.3?

**Comment by xiaolp** [comment]
my shared hosting only support <5.3 ,not choice 👍

**Comment by nezamy** [comment]
Ok, I can't do this for some reasons.
you can try doing some things like.
1 - Replace shortcut array `[]` to `array()` from all file in /system folder
2 - Remove `callable` from class route line 145 `callable $callback` to `$callback` 
3 - Replace line 495 to `$this->{$k} = $v;`
4 - Don't use callback function, use this way
```php
class home
{
    function pages(){
        echo 'Home page Content';
    }
}
$route->get('/', ['home', 'pages']);
// OR
$home = new home;
$route->get('/', [$home, 'pages']);
// OR
$route->get('/', 'home@pages');
```

Tell me if you get errors.
