### ISSUE TITLE
controller/resource doesn't work for me

### ISSUE THREAD

**Issue by arily** [nezamy/route#31]
app()->route->group('/AddressList',function(){
app()->route->controller('/','arily\\accounting\\plugin\\AddressList\\WebController');
});
//or
app()->route->controller('/AddressList','arily\\accounting\\plugin\\AddressList\\WebController');

neither will work for me.
will output 404 Not Found.

namespace arily\accounting\plugin\AddressList;
app()->web = new WebController;
app()->route->group('/AddressList',function(){
app()->route->any('/*',function(){
call_user_func_array([app()->web,$this[1].'_'.app('request')->method],array_slice($this->getArrayCopy(),2));
});
});
//this will work but it doesn't nearly as convince as the Controller/Resource provided by route->controller

**Comment by nezamy** [comment]
@arily Thank you for using the Route
I update Route class, maybe this update fix your issue, if not you can show me what in WebController

**Comment by arily** [comment]
@nezamy I updated, This time I am getting a fatal error.

> Fatal error :  Uncaught TypeError: Argument 1 passed to System\Route::route() must be of the type array, string given, called in /test/vendor/nezamy/route/system/Route.php on line 266 and defined in /test/vendor/nezamy/route/system/Route.php:99
> Stack trace:
> #0 /test/vendor/nezamy/route/system/Route.php(266): System\Route->route('POST_GET', '/AddressList', Array, Array)
> #1 /test/public/index.php(58): System\Route->controller('/AddressList', 'arily\\accountin...')
> #2 {main}
>   thrown in /test/vendor/nezamy/route/system/Route.php on line 99
> 

and same result in group.

Here's the WebController

```
<?php
namespace arily\accounting\plugin\AddressList;

class WebController {
	public function post_getIndex(){
		require_once __DIR__.'/public/top.php';
		echo 'It works';
	}
	public function __call($name, $arguments) {
		$real_name = '_' . $name;
		require_once __DIR__.'/public/top.php';
		if (method_exists($this,$real_name)){
			call_user_func_array([$this,$real_name],$arguments);
		} else {
			require __DIR__.'/public/not_found.php';
		}
	}
	public function index(){
		$this->post_getIndex();
	}
	public function _post_getIndex(){
		$this->post_getIndex();
	}
	public function _test_get(){
		echo 'Get test',PHP_EOL;
	}
}
```

**Comment by arily** [comment]
It seems caused by missing '[]' in Route.php  at line 266.
and I tried 
```
	public function getHome(){
		pre('get home');
	}
```
it works.
so it might be that this type of method which combined different request method won't work for now?
```
    // POST or GET controller/
    public function post_getIndex(){
        // do something here
    }
```
