### ISSUE TITLE
Datatables serverside 

### ISSUE THREAD

**Issue by andikaryanto** [nezamy/route#33]
Array to string conversion in 
D:\xampp\htdocs\Resto\vendor\nezamy\route\system\Request.php online 76

when i use datatables server side i got his error because 
datatable GET method would be like this if i convert to json

{"draw":"1",
**"columns"**:[
{"data":"0","name":"","searchable":"false","orderable":"true","search":{"value":"","regex":"false"}},{"data":"1","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"2","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"3","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"4","name":"","searchable":"true","orderable":"false","search":{"value":"","regex":"false"}}
],
"order":[
{"column":"3","dir":"desc"}
],
"start":"0",
"length":"5",
"search":{"value":"","regex":"false"},"_":"1561609807581"}

the **column** parameter is an array

**Comment by nezamy** [comment]
I don't understand the problem can you share route code
