### ISSUE TITLE
having a choice to bypass 'exit;' in route->end() ?

### ISSUE THREAD

**Issue by arily** [nezamy/route#34]
I am tring to send a file generated by php to client, and I used "before" to create an html template. And 'before' runs before get so I have no clue what my contents will be.
then I tried using ob to catch all template and also my content.

here's an example code:
```
app()->nowrap =false;
$route->before('/',function(){
  ob_start();
  ...
  app()->heading = ob_get_clean();
}
$route->get('/file',function(){
  echo file_get_contents(...);
}
$route->after('/',function(){
  header('Content-Type: text/plain');
  app()->nowrap = true;
  ob_start();
  ...
  app()->footing = ob_get_clean();
}
ob_start();
$route->end();
$content = ob_get_clean();
if (!app()->nowrap) echo app()->heading;
echo $content;
if (!app()->nowrap) echo app()->footing;


```
function end(bool $exit = true){
...
if ($exit){
    exit;
}
```

**Comment by nezamy** [comment]
`before` and `after`, and `use` is designed such middleware, Not for output content
You need to use view template instead
see this https://github.com/nezamy/view

**Comment by arily** [comment]
got it! will check it out! thanks!!
