### ISSUE TITLE
.htaccess error

### ISSUE THREAD

**Issue by ohari5336** [nezamy/route#35]
![image](https://user-images.githubusercontent.com/22674877/70377909-10485a80-1940-11ea-982a-7c46b331074a.png)

when I use your htaccess file and open site its download file like this

but when I remove your htaccess file then not working this type URL

https://example.com/about

and working url is 

https://example.com/index.php/about

soo please see this and solve this and my server versions are

![image](https://user-images.githubusercontent.com/22674877/70377974-fb1ffb80-1940-11ea-8bbb-a939ed806bdc.png)

**Comment by nezamy** [comment]
@ohari5336  Try to remove the first line from .htaccess
```AddHandler application/x-httpd-php56s .php```

**Comment by ohari5336** [comment]
it's working on my local server 

in my hosting some technical problems so currently I do not check on my site but maybe also it's work on server

thanks for solving this
