### ISSUE TITLE
problems with the end () method, does not show full site

### ISSUE THREAD

**Issue by NeftaliAcosta** [nezamy/route#37]
I have the following directory tree:

project
├── app
│   ├── controllers
│   │   ├── routeControllers.php
│   │   └── systemControllers.php
│   ├── models
│   ├── templates
│   │   └── homeTemplate.php
│   ├── pages
│   │   ├── home.php
│   │   ├── about.php
│   │   └── contact.php
├── include
│   │   ├── system.php
├── resources
├── vendor
 ── index.php

1.- index.php includes system.php
2.- system.php loads the libraries and calls the system controller.
```
<?php

	/**
	 * Requiere los controladores y librerias de JCP
	 */
	require_once __DIR__.'/../app/auto_loader.php';
	/**
	 * Requiere las librerias de composer
	 */
	require_once __DIR__.'/../vendor/autoload.php';

	require_once 'config.php';
	Use App\Controllers\systema;
	$init = new systema();
	$init->start();
```

3.- The system controller instantiates the route controller e requires the main template:
```
<?php 

	namespace  App\Controllers;

	use App\Controllers\Route;


	class systema{
		private $route;

		public function __construct(){
			$this->route = new Route();
	    }

		public function start(){
			require_once(__DIR__.'/../../app/templates/homeTemplate.php');
		}
	}
```

4.- The main template makes use of the "route" object instantiated in the constructor, from there it accesses the "pages" function of the route controller to show each section of the site.
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<?php 
		/*
			Route object
		 */
        $this->route->pages();
	 ?>
</body>
</html>
```

5.- route Controller.php indicates which page to include according to the path.

```
<?php 
	
	namespace  App\Controllers;


	class Route{
		private $route;


		public function __construct(){
			$app            = \System\App::instance();
			$app->request   = \System\Request::instance();
			$app->route     = \System\Route::instance($app->request);
			$this->route = $app->route;
		}


		public function pages(){
			$this->route->get('/', function() {
			    echo 'Test page';
			});

			$this->route->get('/about', function() {
			   echo 'Test page';
			});


			$this->route->get('/test', function() {
			    echo 'Test page';
			});

			$this->route->end();
		}

	}
```

**The problem**: The route handler if it accesses and correctly displays each section according to the page, but it doesn't show the whole template, it pauses, or ends, right where I am accessing the object from the homeTemplate.php template

When I delete "$this->route->end();" the template it is displayed complete but the content of the path is not displayed.

Example: With $this->route->end();
![image](https://user-images.githubusercontent.com/15948880/84227371-dea87b80-aaa9-11ea-9e7d-4b816d7cbc21.png)

Example With out #this->route->end();
![image](https://user-images.githubusercontent.com/15948880/84227520-42cb3f80-aaaa-11ea-916c-20d0ac558383.png)

**Comment by nezamy** [comment]
@NeftaliAcosta you are using the route wrong
Should be use it to map all site URIs
Before any output  when you call $route->end() you end the output too
You can use https://github.com/nezamy/view for handling your html code
So, the right way  routes should be registered in file. And use controller to send output
I will upload my structure to understand what I mean

**Comment by nezamy** [comment]
@NeftaliAcosta I just upload a ready template to use on https://github.com/nezamy/just

**Comment by NeftaliAcosta** [comment]
> @NeftaliAcosta I just upload a ready template to use on https://github.com/nezamy/just

Excellent, I will use it to better manage my templates.
Thank you very much for the help. <3
