### ISSUE TITLE
Error on require

### ISSUE THREAD

**Issue by Nevercold** [nezamy/route#38]
Hey, I get an error on installing.
`  [RuntimeException]
  Could not load package nezamy/route in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.*: Invalid version string "^1.*"
`
` [UnexpectedValueException]
  Could not parse version constraint ^1.*: Invalid version string "^1.*"
`

I've already tried everything, but don't know why.

**Comment by catodiDev** [comment]
@Nevercold I had the same situation, I could not install it and I could solve it by updating the composer to version 1.10.13

**Comment by ntd187** [comment]
same error, are there any way to update only chosen vendor (not all)?

**Comment by nezamy** [comment]
@Nevercold, @ntd187 Ok, I tested and I faced the same error.
I solved this problem by removing the composer and reinstall the latest version

@ntd187 You just update the composer version itself, not the library or vendor
