### ISSUE TITLE
Error composer update

### ISSUE THREAD

**Issue by JMultimidia** [nezamy/route#39]
Hi!, Help-me please.
Whenever I need to perform a composer update the following error occurs:

 [RuntimeException]                                                                                                                                  
  Could not load package nezamy/route in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.*: Invalid vers  
  ion string "^1.*"

**Comment by hoxsec** [comment]
This error is fixed now, please try the following: <br/>**composer update -v**
