### ISSUE TITLE
Calling by class method doesn't work for me

### ISSUE THREAD

**Issue by hhdivil** [nezamy/route#8]
I get an error with this:
`$user = new Controllers\UserController;
$route->get('/', [$user, 'pages']);`

`Object of class Controllers\UserController could not be converted to string in /var/www/html/test/vendor/nezamy/route/system/Route.php on line 435`

Also calling it like this doesn't work either:
`$route->get('/', ['Controllers\UserController', 'pages']);`

Then you get this:
`Fatal error: Uncaught Exception: Callable error on Controllers\UserController -> view try with namespace`

**Comment by hhdivil** [comment]
It seems removing `throw new \Exception("Callable error on {$callback[0]} -> {$callback[1]} try with namespace");` fixes the issue ?

**Comment by nezamy** [comment]
Yes, you are right.
It's fixed.
